# Jekyll Primer theme _custom.yml
# https://github.com/pages-themes/primer/blob/master/_config.yml

title: APLS Documentation

exclude:
  - node_modules
  - script

sass:
  style: :compressed

# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs@v0.5.4

github:
  private: false
  license:
    name: CC BY-NC-SA 4.0
  source:
    branch: "main"
    path: "/"
  repository_url: https://github.com/djvill/APLS

lang: en-US

collections:
  versions:
    sort_by: version

########################################
#### Config for just-the-docs theme ####
########################################

##Favicon
favicon_ico: /assets/img/1f34e.svg

##Search
##Config: https://just-the-docs.github.io/just-the-docs/docs/configuration/#search
search:
  heading_level: 3
  previews: 5

##Footer
##Config: https://just-the-docs.github.io/just-the-docs/docs/configuration/#footer-content
back_to_top: false
last_edit_timestamp: true
last_edit_time_format: "%B %-d, %Y"
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/djvill/APLS" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

##Color scheme
##Config: https://just-the-docs.github.io/just-the-docs/docs/customization/#custom-schemes
color_scheme: apls
# color_scheme: apls-dark

##Callouts (e.g., "Note", "Warning")
##Use: https://just-the-docs.github.io/just-the-docs/docs/ui-components/callouts/
##Config: https://just-the-docs.github.io/just-the-docs/docs/configuration/#callouts
callouts:
  note:
    title: Note
    color: yellow
    icon: /assets/img/fa-circle-info.png  # Not implemented yet. Need to use JS to inject icon into .note::before
  warning:
    title: Warning
    color: red

##Google Analytics
ga_tracking: G-TT6NWBCLVW 
ga_tracking_anonymize_ip: true  # Use GDPR compliant Google Analytics settings
