---
title: Phonemic transcription with the DISC alphabet
subtitle: Archive of Pittsburgh Language and Speech (APLS)
author: Dan Villarreal
date: "Last updated `r gsub(' 0', ' ', format(Sys.Date(), '%B %d, %Y'))`"
output: 
  html_document:
    toc: yes
    toc_float: 
      collapsed: no
    anchor_sections: 
      style: "icon"
    md_extensions: -smart
    includes:
      in_header: ../site-assets/header.html
    css: ../site-assets/css/doc.css
    number_sections: yes
    pandoc_args: "--shift-heading-level-by=-1"
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE)
```

```{css}
/* Inline DISC examples */
li code:not(.counterex), p code:not(.counterex) {
  font-weight: bold;
}

li code.counterex, p code.counterex {
  font-weight: normal;
  text-decoration: line-through;
}

/* Consonants & vowels tables */
.table-condensed {
  max-width: 500px;
  font-size: 1.2em;
}
td:nth-child(2) {
  font-family: monospace;
}
td:nth-child(4) {
  font-family: monospace;
}

/* Syllabification table */
#syll-table.table-condensed {
  max-width: 300px;
}
#syll-table td:nth-child(1) {
  font-family: monospace;
}
#syll-table td:nth-child(2) {
  font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
}

/* Extra padding for list elements */
ul {
  padding-bottom: 6px;
}
li {
  padding-top: 2px;
}
```

The **DISC phonemic alphabet** represents speech sounds by creating a one-to-one mapping between sounds and symbols, much like the IPA.
_Unlike_ the IPA, the DISC phonemic alphabet only uses symbols that appear on a standard keyboard.

APLS uses a subset of DISC relevant to North American Englishes.
In APLS, we use DISC symbols for _phonemic_ representations of sounds, not _phonetic_ representations.
As a result, the APLS subset of DISC doesn't have symbols for [ɾ] or [ʔ]; in North American Englishes, these surface only as allophones of /t/.



## DISC consonants


### Non-syllabic consonants

| IPA | DISC |    English   |      DISC     |
|-----|------|--------------|---------------|
|  p  |   p  | **p**at      |  **p**{t      |
|  b  |   b  | **b**ad      |  **b**{d      |
|  t  |   t  | **t**ack     |  **t**{k      |
|  d  |   d  | **d**ad      |  **d**{d      |
|  k  |   k  | **c**ad      |  **k**{d      |
|  ɡ  |   g  | **g**ame     |  **g**1m      |
|  ŋ  |   N  | ba**ng**     |  b{**N**      |
|  m  |   m  | **m**ad      |  **m**{d      |
|  n  |   n  | **n**at      |  **n**{t      |
|  l  |   l  | **l**ad      |  **l**{d      |
|  ɹ  |   r  | **r**ad      |  **r**{d      |
|  f  |   f  | **f**ad      |  **f**{d      |
|  v  |   v  | **v**at      |  **v**{t      |
|  θ  |   T  | **th**in     |  **T**In      |
|  ð  |   D  | **th**en     |  **D**En      |
|  s  |   s  | **s**ap      |  **s**{p      |
|  z  |   z  | **z**ap      |  **z**{p      |
|  ʃ  |   S  | **sh**eep    |  **S**ip      |
|  ʒ  |   Z  | mea**s**ure  |  mE**Z**\@r   |
|  h  |   h  | **h**ad      |  **h**{d      |
|  tʃ |   J  | **ch**eap    |  **J**ip      |
|  dʒ |   _  | **j**eep     |  **\_**ip     |
|  w  |   w  | **w**et      |  **w**Et      |
|  j  |   j  | **y**et      |  **j**Et      |


### Syllabic consonants

| IPA | DISC |    English   |      DISC     |
|-----|------|--------------|---------------|
|  ɱ̩  |   F  | idealis**m** |  2dilIz**F**  |
|  n̩  |   H  | burd**en**   |  b3rd**H**    |
|  l̩  |   P  | dang**le**   |  d{Ng**P**    |


## DISC vowels 

### Monophthongs not before /ɹ/ {#monophthongs-not-before-r}

| IPA | DISC |    English   |      DISC     |
|-----|------|--------------|---------------|
|  ɪ  |   I  | k**i**t      |  k**I**t      |
|  ε  |   E  | dr**e**ss    |  dr**E**s     |
|  æ  |   {  | tr**a**p     |  tr**{**p     |
|  ʌ  |   V  | str**u**t    |  str**V**t    |
|  ɑ  |   Q  | l**o**t      |  l**Q**t      |
|  ʊ  |   U  | f**oo**t     |  f**U**t      |
|  ə  |   \@ | comm**a**    |  kQm**\@**    |
|  i  |   i  | fl**ee**ce   |  fl**i**s     |
|  ɔ  |   \$ | th**ough**t  |  T**\$**t     |
|  u  |   u  | g**oo**se    |  g**u**s      |


### Monophthongs before /ɹ/ {#monophthongs-before-r}

| IPA | DISC |    English   |      DISC     |
|-----|------|--------------|---------------|
|  ɑɹ |  #r  | st**ar**t    |  st**#r**t    |
|  ɔɹ |  \$r | f**or**ce    |  f**\$r**s    |
|  ɚ  |  \@r | lett**er**   |  lEt**\@r**   |
|  ɝ  |  3r  | n**ur**se    |  n**3r**s     |
|  ɪɹ |  7r  | n**ear**     |  n**7r**      |
|  εɹ |  8r  | squ**are**   |  skw**8r**    |
|  ʊɹ |  9r  | c**ure**     |  kj**9r**     |


### Diphthongs

| IPA | DISC |    English   |      DISC     |
|-----|------|--------------|---------------|
|  eɪ |   1  | f**a**ce     |  f**1**s      |
|  aɪ |   2  | pr**i**ce    |  pr**2**s     |
|  ɔɪ |   4  | ch**oi**ce   |  J**4**s      |
|  oʊ |   5  | g**oa**t     |  g**5**t      |
|  aʊ |   6  | m**ou**th    |  m**6**T      |



## Transcribing words using DISC

As noted above, DISC transcription is phonemic rather than phonetic.
Here are some other things to note:

- Monophthongs before /ɹ/ should always be transcribed with the DISC `r` symbol (see examples [above](#monophthongs-before-r))
	- Exception: the speaker cuts off the word before an /ɹ/ (e.g., cutting off _start_ as `sta~[st#]`
- IPA makes a distinction between _stressed_ central vowels /ʌ ɝ/ and _unstressed_ central vowels /ə ɚ/. Similiarly, use DISC `V`/`3r` for _stressed_ vowels and `@`/`@r` for _unstressed_ vowels
	- Exception: Always use `3r` for _-burg(h)_, even if it's unstressed (e.g., _Pittsburghese_ is `pItsb3rgiz` not <code class="counterex">pItsb\@rgiz</code>)
- Use the DISC symbols for syllabic consonants, `F`/`H`/`P`, rather than <code class="counterex">\@m</code>/<code class="counterex">\@n</code>/<code class="counterex">\@l</code> (see examples [above](#disc-consonants))
	- Exception: Don't use these symbols for onsets (e.g., _Panera_ is `p@n8r@`, not <code class="counterex">pH8r\@</code>)
- For word-final high front vowels, use `i` rather than `I` (i.e., we assume universal [_happy_-tensing](https://en.wikipedia.org/wiki/Phonological_history_of_English_close_front_vowels#Happy-tensing))
- When /ŋ/ comes before a vowel or syllabic consonant, assume it's followed by /g/ (e.g., _dangle_ is `d{NgP`, not <code class="counterex">d{NP</code>)
- Don't forget that _nk_ in English spelling is usually /ŋk/ (DISC `Nk`) rather than /nk/ (DISC <code class="counterex">nk</code>)
- If you have the _cot_–_caught_ merger in production and/or perception, ask a non-merged friend to help you decide whether to transcribe `Q` or `$`.
- Unstressed vowels can be tricky!
  - For "schwi", use `@` rather than `I` (e.g., _breathless_ is `brETl@s` not <code class="counterex">brETlIs</code>)
  - Same for _'s_ after a sibilant (e.g., _Lutz's_ is `lVts@z` not <code class="counterex">lVtsIz</code>)
  - Again, use `@` for unstressed mid-central vowels ("schwa") and `@r` pre-/ɹ/
- There's no [ɾ] symbol; instead, use `t` or `d` as suggested by orthography, even if it doesn't match the voicing of the surface segment (e.g., _Bettis_ is `bEtIs`, not <code class="counterex">bEdIs</code>)

## Suggesting new dictionary entries

APLS uses two sources to look up phonemic representations: (1) the Unisyn English dictionary (which is supposed to be a universal English dictionary), and (2) a [custom dictionary](https://raw.githubusercontent.com/djvill/APLS/main/files/custom-dictionary/aplsDict.txt).
Occasionally you'll run across a word that needs to be added to APLS's custom dictionary.
Most often this will be a Pittsburgh/western PA geographic name (e.g., neighborhoods like _Shadyside_, municipalities like _Sewickley_, streets like _Baum_, schools like _Milliones_), a brand name (e.g., _Highmark_, _Panera_), or a Pittsburgh lexical feature (e.g., _redd_, _gumband_).
However, there are words that aren't Pittsburgh-specific that are absent from Unisyn, sometimes unexpectedly;
for example, we've had to manually add entries for _artsy_, _bachelorette_, _homie_, _Kwanzaa_, _microbrew_, _stepdad_, _tarp_, and _y'all_ (among others).


If a word falls into one of the preceding categories, it should be added to the APLS dictionary.
On the other hand, if a word is unlikely to be used by more than one speaker, it's better to just use an [inline DISC code](Transcription-Convention#novel-words).


Everything from the previous sections applies to new words that you suggest for the custom dictionary, plus the following:

1. If applicable, you can suggest 2+ phonemic representations per word (but this is optional)
1. Use the speech community's pronunciation(s)
1. Add symbols to mark syllabification and stress


### Multiple phonemic representations

APLS's custom dictionary can contain multiple phonemic representations for any given word.
For example, the first vowel in _Lawrenceville_ can rhyme with either _shore_ or _far_ (`$r` or `#r`).
In that case, just suggest the full DISC representation twice: `'l$r-Hs-"vIl` or `'l#r-Hs-"vIl`.


Keep in mind that these are _phonemic_ representations.
This means that we don't add separate entries that reflect variable phonological processes like consonant cluster deletion.
For example, even though Pittsburghers pronounce _gumband_ as both [ˈgʌmbæ**nd**] and [ˈgʌmbæ**n**], only `'gVm-b{nd` should go in APLS's custom dictionary.


### Use the speech community's pronunciation(s)

APLS's dictionary entries should reflect Pittsburgh English speakers' mental lexicons.
That means that if Pittsburgh English speakers have a different mental representation for a word than we'd expect based on the word's spelling or our experience, APLS's dictionary needs to include the local phonemic representation.
For example, Pittsburghers often pronounce _Carnegie_ as [kɑɹ.ˈneɪ.gi], whereas non-Pittsburghers almost always use [ˈkɑɹ.nə.gi].
In the course of a single transcription, it's impossible to know whether a particular pronunciation is widespread, so use your best judgment.
As mentioned [above](#multiple-phonemic-representations), you can suggest multiple representations for a word, as long as they're _phonemic_ representations.


### Syllabification and stress

Use the following symbols for syllabification and stress **only** if suggesting new entries for the APLS custom dictionary (not for DISC transcription in pronounce codes):

<div id="syll-table">

| DISC | Function          |
|------|-------------------|
|   -  | Syllable boundary |
|   '  | Primary stress    |
|   "  | Secondary stress  |

</div>

For example, _Pennsylvanian_ is `"pEn-sP-'v1n-jH`. 
Stress markers go before any other DISC symbols, but (if applicable) after the syllable boundary.
Unstressed syllables get no stress markers.

A few finer points:

- Every _complete_ word has one primary-stressed syllable. _Incomplete_ words with hesitations might not have a primary-stressed syllable, but the APLS custom dictionary won't have incomplete words
	- Most words don't have secondary stress. Compounds often do have secondary stress (e.g., _Sandcastle_ is `'s{nd-"k{-sP`)
- Use secondary stress for city-name morphemes _-burg(h)_, _-ville_, _-vale_, _-dale_, _-town_, etc.
	- Exception: There are derivational affixes that change the stress pattern (e.g., _Pittsburgh_ is `"pIts-"b3rg`, but _Pittsburghese_ is `"pIts-b3r-'giz`)
- Intervocalic consonants should be syllabified as onsets rather than codas (e.g., 
	- Exception 1: Intervocalic /ɹ/ should be syllabified as a coda (e.g., _Panera_ is `p@-'n8r-@` not <code class="counterex">p\@-'n8-r\@</code>)
	- Exception 2: In environments where prevocalic /t/ becomes [ʔ] (e.g., before /n̩/), the /t/ should be syllabified as a coda (e.g., _outen_ is `'6t-H` not <code class="counterex">'6-tH</code>)




```{js, file="../site-assets/js/doc.js"}
/* Common documentation JS */
```

```{js}
/* Add headers above consonants and vowels tables */
var newHead = `
	<tr>
		<th style='empty-cells:hide; border-bottom:hidden;' colspan='2'/>
		<th style='border-bottom:hidden; padding-bottom:0; padding-left:3px; padding-right:3px; text-align:center;' colspan='2'>
			<div style='border-bottom: 1px solid #ddd; padding-bottom: 5px;'>Example word</div>
		</th>
	</tr>
`;
Array.from($("#disc-consonants tr.header"))
	.map(a => a.insertAdjacentHTML('beforebegin', newHead));
Array.from($("#disc-vowels tr.header"))
	.map(a => a.insertAdjacentHTML('beforebegin', newHead));
```


